### ISSUE TITLE
Ajouter de la documentation Vitepress pour tous les composants (Epic)

### ISSUE THREAD

**Issue by laruiss** [dnum-mi/vue-dsfr#668]
Ajouter de la documentation pour :
- [x] #669
- [x] DsfrAlert
- [x] #670
- [x] DsfrBadge
- [x] #671
- [x] DsfrButton
- [x] DsfrButtonGroup
- [x] DsfrCallout
- [x] #695
- [x] DsfrCheckbox et DsfrCheckboxSet
- [x] #713
- [x] DsfrErrorPage
- [x] #723
- [x] #725
- [x] DsfrFileDownloadList
- [x] DsfrFileUpload
- [x] DsfrFollow
- [x] DsfrFooter
- [x] DsfrFooterLinkList
- [x] DsfrFooterPartners
- [x] DsfrFranceConnect
- [x] DsfrHeader
- [x] DsfrHeaderMenuLink
- [x] DsfrHeaderMenuLinks
- [x] DsfrHighlight
- [x] DsfrInput
- [x] DsfrInputGroup
- [x] DsfrLanguageSelector
- [x] DsfrLogo
- [x] DsfrModal
- [x] #1097
- [x] DsfrNavigationItem
- [x] DsfrNavigationMegaMenu
- [x] DsfrNavigationMegaMenuCategory
- [x] DsfrNavigationMenu
- [x] DsfrNavigationMenuItem
- [x] DsfrNavigationMenuLink
- [x] DsfrNewsLetter
- [x] #672
- [x] DsfrPagination
- [x] DsfrPicture
- [x] DsfrQuote
- [x] DsfrRadioButton et DsfrRadioButtonSet
- [x] DsfrSearchBar
- [x] #688
- [x] DsfrSegmented
- [x] DsfrSegmentedSet
- [x] DsfrSelect
- [x] DsfrShare
- [x] DsfrSideMenu (rassembler les enfants ?)
- [x] DsfrSideMenuButton
- [x] DsfrSideMenuLink
- [x] DsfrSideMenuList
- [x] DsfrSideMenuListItem
- [x] DsfrSkipLinks
- [x] DsfrSocialNetworks
- [x] DsfrStepper
- [x] DsfrSummary
- [x] DsfrTabContent
- [x] DsfrTabItem
- [x] DsfrTable (rassembler les enfants ?)
- [x] DsfrTableCell
- [x] DsfrTableHeader
- [x] DsfrTableHeaders
- [x] DsfrTableRow
- [x] DsfrTabs
- [x] DsfrTag
- [x] DsfrTags
- [x] DsfrTile et DsfrTiles
- [x] DsfrToggleSwitch
- [x] DsfrTooltip
- [x] DsfrTranscription
- [x] DsfrVideo

**Comment by laruiss** [comment]
Ajouter de la documentation pour :
- [ ] DsfrAccordion et DsfrAccordionsGroup
- [ ] DsfrAlert
- [ ] DsfrBackToTop
- [ ] DsfrBadge
- [ ] DsfrBreadcrumb
- [ ] DsfrButton
- [ ] DsfrButtonGroup
- [ ] DsfrCallout
- [ ] DsfrCard
- [ ] DsfrCheckbox et DsfrCheckboxSet
- [ ] DsfrConsent
- [ ] DsfrErrorPage
- [ ] DsfrFieldset
- [ ] DsfrFileDownload
- [ ] DsfrFileDownloadList
- [ ] DsfrFileUpload
- [ ] DsfrFollow
- [ ] DsfrFooter
- [ ] DsfrFooterLinkList
- [ ] DsfrFooterPartners
- [ ] DsfrFranceConnect
- [ ] DsfrHeader
- [ ] DsfrHeaderMenuLink
- [ ] DsfrHeaderMenuLinks
- [ ] DsfrHighlight
- [ ] DsfrInput
- [ ] DsfrInputGroup
- [ ] DsfrLanguageSelector
- [ ] DsfrLogo
- [ ] DsfrModal
- [ ] DsfrNavigation
- [ ] DsfrNavigationItem
- [ ] DsfrNavigationMegaMenu
- [ ] DsfrNavigationMegaMenuCategory
- [ ] DsfrNavigationMenu
- [ ] DsfrNavigationMenuItem
- [ ] DsfrNavigationMenuLink
- [ ] DsfrNewsLetter
- [ ] DsfrNotice
- [ ] DsfrPagination
- [ ] DsfrPicture
- [ ] DsfrQuote
- [ ] DsfrRadioButton et DsfrRadioButtonSet
- [ ] DsfrSearchBar
- [ ] DsfrSelect
- [ ] DsfrShare
- [ ] DsfrSideMenu (rassembler les enfants ?)
- [ ] DsfrSideMenuButton
- [ ] DsfrSideMenuLink
- [ ] DsfrSideMenuList
- [ ] DsfrSideMenuListItem
- [ ] DsfrSkipLinks
- [ ] DsfrSocialNetworks
- [ ] DsfrStepper
- [ ] DsfrSummary
- [ ] DsfrTabContent
- [ ] DsfrTabItem
- [ ] DsfrTable (rassembler les enfants ?)
- [ ] DsfrTableCell
- [ ] DsfrTableHeader
- [ ] DsfrTableHeaders
- [ ] DsfrTableRow
- [ ] DsfrTabs
- [ ] DsfrTag
- [ ] DsfrTags
- [ ] DsfrTile et DsfrTiles
- [ ] DsfrToggleSwitch
- [ ] DsfrTranscription
- [ ] DsfrVideo

**Comment by laruiss** [comment]
Pour chacun, voici (un brouillon de) la DoD :

- reprise du début de la documentation officielle qui présente le composant en rajoutant les liens avec les props
- lien vers le storybook
- lien vers la doc officielle DSFR du composant
- récapitulatif des props dans un tableau (nom, type, défaut, requis)
- récapitulatif des événements dans un tableau  (nom, type de payload si présent)
- exemples
- ajouter un lien dans la sidebar (`.vitepress/config.ts`, dans `themeConfig.sidebar`)
- ajouter un lien dans `docs/composants.md`

Parfois, ce serait bien de rajouter :
- astuces (optionnel)

S’inspirer de [DsfrAlert](https://docs.vue-ds.fr/composants/DsfrAlert)
